import { ApplicationService } from "../../../system.js";
import { SystemEvent, Events } from "../../types/system-event.js";
import { Result } from "../../types/result.js";
import { Problem } from "../../types/problem.js";

/**
 * Raw data row from `vocabulary.phrases` table as returned from Supabase
 *
 * @typedef {Object} RawPhrase
 * @property {string} id - UUID generated by the database.
 * @property {string} created_at - ISO 8601 timestamp string.
 * @property {string} phrase - Natural language phrase users can search.
 * @property {string} condition - SQL condition fragment applied to the wines table.
 * @property {string} definition - Short human-readable explanation of the phrase.
 * @property {string|null} join_required - indicates a join is required to use the phrase in the SQL query
 */

/**
 * Raw data row from `vocabulary.terms` table as returned from Supabase
 *
 * @typedef {Object} RawKeyword
 * @property {string} id - UUID generated by the database.
 * @property {string} created_at - ISO 8601 timestamp string.
 * @property {string} term - Searchable keyword entered by users.
 * @property {string} definition - Short human-readable explanation of the term.
 * @property {string} attribute - Column name on the wines table this term maps to.
 * @property {"=" | ">=" | "<=" | "ILIKE"} operator - SQL operator applied to the attribute.
 * @property {string} value - Value used in the SQL comparison (stored as string from DB).
 */

/**
 * Combined search vocabulary pulled from Supabase
 *
 * @typedef {Object} Vocabulary
 * @property {RawKeyword[]} queryTerms
 * @property {RawPhrase[]} queryPhrases
 */

/**
 * A map of structured SQL query components; they may include JOINs and other clauses or templates that
 * must be expanded into a valid SQL query to pass to the database
 * @typedef {Object} QueryFragment
 * @property {string} condition
 * @property {string|null} joinKey
 */


/**
 * Ensures attributes that are scalar values or booleans are coerced to the correct type to
 * ensure predictable SQL queries
 */
const COERCED_TYPES = {
  sweetness: (v) => Number(v),
  acidity: (v) => Number(v),
  minerality: (v) => Number(v),
  price: (v) => Number(v),
  vintage: (v) => Number(v),
  sparkling: (v) => v === "true",
};

/**
 * Enum of SQL functions **defined on the database** mapped to supported search strategy names
 * @readonly
 * @enum {string}
 */
const SQL_FUNC = Object.freeze({
  ProductDiscoveryStrategy: "search_wines_product_discovery",
  ProductLookUpStrategy: "search_wines_product_lookup",
});

/**
 * Manages the vinely search pipeline end-to-end
 */
export default class QueryService extends ApplicationService {
  static service = "QueryService";
  static bootstrap = true;

  #isReady = false;
  #currentStrategy;
  #dbClient;
  #logger;
  #sandbox;
  #vocabularyMap;

  /**
   * @param {ISandbox} sandbox
   */
  constructor(sandbox) {
    super();

    try {
      this.#dbClient = sandbox.my.Database.getClient();
      this.#sandbox = sandbox;
      this.#logger = sandbox.core.logger.getLoggerInstance();

      this.#loadVocabulary()
        .then(this.#buildLocalVocabularyMap)
        .then((vocabMap) => {
          this.#vocabularyMap = vocabMap;
          this.#isReady = true;
        })
        .catch((ex) => {
          // For exceptions that occur during the async vocabulary loading process
          this.#logger.log(
            `INTERNAL_ERROR (${QueryService.service}): **EXCEPTION ENCOUNTERED** while bootstrapping the search vocabulary. See details -> ${ex.message}`
          );
        });
    } catch (ex) {
      // For exceptions that occur while calling the constructor
      this.#logger.log(
        `INTERNAL_ERROR (${QueryService.service}): **EXCEPTION ENCOUNTERED** while starting the service. See details -> ${ex.message}`
      );
    }
  }

  /**
   * Creates a local map of search keywords and phrases for realtime translation to SQL queries
   * @param {Vocabulary} vocabulary
   * @returns {{keywords: QueryFragment, phrases: QueryFragment}}
   */
  #buildLocalVocabularyMap({ queryPhrases, queryTerms }) {
    const phrases = queryPhrases.reduce((res, currentItem) => {
       const phrase = currentItem.phrase //.toLowerCase().trim();
       const length = phrase.split(/\s+/).length;

       if (!res[length]) {
         res[length] = {};
       }

      res[length][phrase] = {
        condition: currentItem.condition,
        joinKey: currentItem.join_required ?? null,
      };

      return res;
    }, {});

    const keywords = queryTerms.reduce((res, currentItem) => {
      const formattedValue = COERCED_TYPES[currentItem.attribute]
        ? COERCED_TYPES[currentItem.attribute](currentItem.value)
        : `'${currentItem.value}'`;

      const condition = `${currentItem.attribute} ${currentItem.operator} ${formattedValue}`;

      res[currentItem.term] = {
        condition,
        join: null
      } 

      return res;
    }, {});

    return { keywords, phrases };
  }

  /**
   * Pulls the keywords and search phrases from the database for use in query processing
   * @returns {Promise<Vocabulary>}
   */
  async #loadVocabulary() {
    const { data: queryTerms, error: queryTermsLookupError } =
      await this.#dbClient.schema("vocabulary").from("terms").select();
    const { data: queryPhrases, error: queryPhrasesLookupError } =
      await this.#dbClient.schema("vocabulary").from("phrases").select();

    if (queryTermsLookupError || queryPhrasesLookupError) {
      throw new Error(
        `${
          queryTermsLookupError
            ? queryTermsLookupError.message
            : queryPhrasesLookupError.message
        }`
      );
    }
    return { queryTerms, queryPhrases };
  }

  /**
   * Allows instances of `SearchStrategy` to execute queries against the database (or
   * any other datastore) without knowledge of or need for a direct reference to the database)
   * @param {string} sqlString
   * @param {string} strategyName the name of the current search strategy
   * @returns {Result<Object[] | Problem>
   */
  async #queryRunner(sqlString, strategyName) {
    try {
      const { data, error } = await this.#dbClient.rpc(SQL_FUNC[strategyName], {
        query_sql: sqlString,
      });

      if (error) {
        this.#logger.error(
          `INTERNAL ERROR (${QueryService.service}): The database returned an error while running the search query. See details -> ${error.message}`
        );
        return Result.error(
          Problem.of({
            title: "INTERNAL ERROR",
            detail: "There was an error executing the search query.",
          })
        );
      }

      return Result.ok(!data ? [] : data);
    } catch (ex) {
      // TODO: Generalize exception capture and telemetry push to keep things DRY
      return Result.ok(
        this.#sandbox.my.MiddlewareProvider.Telemetry.createExceptionEvent({
          service: "QueryService",
          ex,
        })
      )
        .tap((exceptionEvent) => {
          console.error(
            `INTERNAL_ERROR (QueryService): **EXCEPTION ENCOUNTERED** while executing a search query. This exception instance will be pushed to the 'telemetry.runtime_exceptions' table in the database with id (${exceptionEvent.detail.header.id}). See details -> ${ex.message}`
          );
          this.#sandbox.my.Events.dispatchEvent(exceptionEvent);
        })
        .map((exceptionEvent) =>
          Result.error(
            Problem.of({
              title: "INTERNAL ERROR",
              detail: "There was an error while executing the search query.",
              instance: `runtime_exceptions/query_service/${exceptionEvent.detail.header.id}`,
            })
          )
        );
    }
  }

  get ready() {
    return this.#isReady;
  }

  /**
   * Sets the search strategy to be used by the service (e.g. product_discovery or product_lookup)
   * @param {SearchStrategy} strategy
   */
  setStrategy(strategy) {
    this.#currentStrategy = strategy;
    this.#currentStrategy.setVocabulary(this.#vocabularyMap);
  }

  /**
   *
   * @param {String} queryString - the raw search query from the client
   * @returns {Result<Object | Problem>}
   */
  async search(queryString) {
    try {
      if (!this.#isReady) {
        return Result.error(
          Problem.of({
            title: "SERVICE UNAVAILABLE",
            detail:
              "There was an error executing the search query; the service is not ready.",
          })
        );
      }

      // We `await` here to ensure any uncaught exceptions in the search strategy are captured below
      return await this.#currentStrategy.search(
        queryString,
        this.#queryRunner.bind(this)
      );
    } catch (ex) {
      // TODO: Generalize exception capture and telemetry push to keep things DRY
      return Result.ok(
        this.#sandbox.my.MiddlewareProvider.Telemetry.createExceptionEvent({
          service: "QueryService",
          ex,
        })
      )
      .tap((exceptionEvent) => {
        console.error(
          `INTERNAL_ERROR (QueryService): **EXCEPTION ENCOUNTERED** while executing a search query. This exception instance will be pushed to the 'telemetry.runtime_exceptions' table in the database with id (${exceptionEvent.detail.header.id}). See details -> ${ex.message}`
        );
        this.#sandbox.my.Events.dispatchEvent(exceptionEvent);
      })
      .map((exceptionEvent) =>
        Result.error(
          Problem.of({
            title: "INTERNAL ERROR",
            detail: "There was an error while executing the search query.",
            instance: `runtime_exceptions/query_service/${exceptionEvent.detail.header.id}`,
          })
        )
      );        
    }
  }
}
